import { Movie } from './movie.model';

export const dummy: Movie[] = [
  {
    id: '1',
    title: 'The Lost Empire',
    description: 'An ancient artifact resurfaces, threatening global war.',
    genre: 'Action',
    duration: '2h 10m',
    image: 'https://placehold.co/600x400?text=The+Lost+Empire',
    rate: '8.2',
    directorName: 'James Stanton',
  },
  {
    id: '2',
    title: 'Dreamcatcher',
    description: 'A girl discovers she can enter dreams and change reality.',
    genre: 'Fantasy',
    duration: '1h 55m',
    image: 'https://placehold.co/600x400?text=Dreamcatcher',
    rate: '7.9',
    directorName: 'Sophia Chen',
  },
  {
    id: '3',
    title: 'Parallel Lies',
    description:
      'A detective finds herself chasing a killer across dimensions.',
    genre: 'Sci-Fi',
    duration: '2h 4m',
    image: 'https://placehold.co/600x400?text=Parallel+Lies',
    rate: '8.0',
    directorName: 'Carlos Romero',
  },
  {
    id: '4',
    title: 'Whispers in the Dark',
    description: 'A haunted town hides secrets best left buried.',
    genre: 'Horror',
    duration: '1h 42m',
    image: 'https://placehold.co/600x400?text=Whispers+in+the+Dark',
    rate: '6.8',
    directorName: 'Amara Blake',
  },
  {
    id: '5',
    title: 'City Pulse',
    description: 'An underground DJ fights corruption with music.',
    genre: 'Drama',
    duration: '2h 0m',
    image: 'https://placehold.co/600x400?text=City+Pulse',
    rate: '7.1',
    directorName: 'Liam Porter',
  },
  {
    id: '6',
    title: 'Eclipse of Hope',
    description: 'An astronaut must choose between family and saving Earth.',
    genre: 'Sci-Fi',
    duration: '2h 20m',
    image: 'https://placehold.co/600x400?text=Eclipse+of+Hope',
    rate: '8.5',
    directorName: 'Olivia Hart',
  },
  {
    id: '7',
    title: 'Beneath the Surface',
    description: 'A diver uncovers a mysterious underwater city.',
    genre: 'Adventure',
    duration: '1h 48m',
    image: 'https://placehold.co/600x400?text=Beneath+the+Surface',
    rate: '7.4',
    directorName: 'David Nasser',
  },
  {
    id: '8',
    title: 'Digital Shadows',
    description: 'Hackers battle for truth in a world run by AI.',
    genre: 'Thriller',
    duration: '2h 12m',
    image: 'https://placehold.co/600x400?text=Digital+Shadows',
    rate: '8.1',
    directorName: 'Reina Kwon',
  },
  {
    id: '9',
    title: 'Café Luna',
    description: 'Two lost souls connect over coffee and fate.',
    genre: 'Romance',
    duration: '1h 36m',
    image: 'https://placehold.co/600x400?text=Cafe+Luna',
    rate: '7.2',
    directorName: 'Marcus Del Rio',
  },
  {
    id: '10',
    title: 'Iron Valley',
    description: 'A retired sheriff returns to protect his hometown.',
    genre: 'Western',
    duration: '2h 5m',
    image: 'https://placehold.co/600x400?text=Iron+Valley',
    rate: '6.9',
    directorName: 'Eli Granger',
  },
  {
    id: '11',
    title: 'Sky Hunters',
    description: 'Elite pilots train for a mission that could end war.',
    genre: 'Action',
    duration: '2h 14m',
    image: 'https://placehold.co/600x400?text=Sky+Hunters',
    rate: '7.7',
    directorName: 'Tanya Brooks',
  },
  {
    id: '12',
    title: 'The Artisan',
    description: 'A woodcarver’s sculptures come to life in strange ways.',
    genre: 'Fantasy',
    duration: '1h 59m',
    image: 'https://placehold.co/600x400?text=The+Artisan',
    rate: '7.5',
    directorName: 'Viktor Ivanov',
  },
  {
    id: '13',
    title: 'Last Bloom',
    description: 'A botanist finds the cure to a deadly virus in the Amazon.',
    genre: 'Adventure',
    duration: '2h 3m',
    image: 'https://placehold.co/600x400?text=Last+Bloom',
    rate: '8.3',
    directorName: 'Chloe Tan',
  },
  {
    id: '14',
    title: 'Crimson Debt',
    description: 'A con artist tries to outrun the mob and his past.',
    genre: 'Crime',
    duration: '1h 58m',
    image: 'https://placehold.co/600x400?text=Crimson+Debt',
    rate: '7.6',
    directorName: 'Harvey Knox',
  },
  {
    id: '15',
    title: 'Before Midnight Falls',
    description: 'A time traveler must stop his future self.',
    genre: 'Sci-Fi',
    duration: '2h 9m',
    image: 'https://placehold.co/600x400?text=Before+Midnight+Falls',
    rate: '8.0',
    directorName: 'Naomi Asher',
  },
  {
    id: '16',
    title: 'Frozen Strings',
    description: 'A violinist rediscovers passion after a tragic loss.',
    genre: 'Drama',
    duration: '1h 46m',
    image: 'https://placehold.co/600x400?text=Frozen+Strings',
    rate: '7.3',
    directorName: 'Alberto Duran',
  },
  {
    id: '17',
    title: 'Pulse Code',
    description: 'A cybernetic soldier questions her reality.',
    genre: 'Thriller',
    duration: '2h 1m',
    image: 'https://placehold.co/600x400?text=Pulse+Code',
    rate: '7.8',
    directorName: 'Yasmin Patel',
  },
  {
    id: '18',
    title: 'Echoes of War',
    description: 'Veterans face ghosts of the battlefield at home.',
    genre: 'Drama',
    duration: '2h 6m',
    image: 'https://placehold.co/600x400?text=Echoes+of+War',
    rate: '7.9',
    directorName: 'Connor James',
  },
  {
    id: '19',
    title: 'Glass Trap',
    description: 'A thief is caught in a deadly heist of her own design.',
    genre: 'Crime',
    duration: '1h 52m',
    image: 'https://placehold.co/600x400?text=Glass+Trap',
    rate: '7.0',
    directorName: 'Renee Laurent',
  },
  {
    id: '20',
    title: 'The Ninth Flame',
    description: 'The last fire mage must stop a city from burning itself.',
    genre: 'Fantasy',
    duration: '2h 11m',
    image: 'https://placehold.co/600x400?text=The+Ninth+Flame',
    rate: '8.4',
    directorName: 'Zane Mori',
  },
];
